### ISSUE TITLE
Mouse Click/Action when a certain pressure is applied?

### ISSUE THREAD

**Issue by creamcast** [Kuuuube/Hover_Distance_Limiter#4]
I think this would be an useful feature to add: trigger a Mouse Click/Keyboard key after applying a certain amount of pressure with the stylus. Some pen tablets like the one im using doesn't support hover distance but it can still use the pressure range cutoff and relative mode so the mouse only moves when your dragging on the tablet (like a trackpad). The only problem is there is no way to lightly tap the stylus and do a click action like you would on a trackpad unless you set those actions on the keyboard. I'm not familiar with making plugins for opentabletdriver yet so i dont really know if this is possible. Perhaps someone familiar with the framework might know if this feature is even necessary (is their an alternative way to get a pen tablet to mimic a trackpad?). I am planning to program the feature in and make the contribution if you think its a good idea or is doable.

**Comment by Kuuuube** [comment]
This is out of the scope of hover distance limiter and also already a feature in base OTD. 

Go to the `Pen Settings` tab and under `Tip Settings` use the `Tip Threshold` slider. This will make the action bound to the pen tip only trigger after some percent of the max tablet's pressure.

**Comment by MotaOcimar** [comment]
Hi @Kuuuube!

First of all, thank you very much for this plugin. With it I can use relative mode without having to raise my hand too much (which, in the long run, makes a lot more difference than some might think, especially in fast-paced games).

I have to agree that this issue is out of the scope of the hover distance limeter plugin.
And I also have to agree that the use case presented by @creamcast is already covered by a built-in OTD feature.

Buuuut, I have another use case and would like to ask if you/we could implement a new plugin with this feature.

The use case is to keep the tip threshold low for a first action (like usual), but add ***another action*** triggered by a ***second threshold***.


Why? Because the pen buttons are not completely stable to click, shaking the pen and adding some noise to the tip position. This little noise can make you misclick (which, again, has a very undesirable side effect during a game, or wathever other situation where you need precision when triggering another pen action besides the tip action).
The second tip action, triggered by the second threshold, will hopefully be extremely more stable.

So what do you think?

Ps.: I have no experience in OTD plugin development. But if you give me some instructions, I could try it on my own.

**Comment by Kuuuube** [comment]
@MotaOcimar

I don't plan on making a plugin to support this but you could take a look at how [CycleBind](https://github.com/Ashesh3/OTDCycleBind) or [Monitor Toggle](https://github.com/Kuuuube/monitor_toggle) work.

CycleBind is a good example of how to parse keys and set up the bindings and Monitor Toggle is a good example of how to connect a filter to a binding (to get pressure data you will need a filter).

If you want further direction on how to create a plugin it would be best to join the OpenTabletDriver discord server.

**Comment by MotaOcimar** [comment]
@Kuuuube, thanks for the references! I'll take a look and do some experiments
